# Generated by Django 4.2.27 on 2026-01-27 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='ình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá bán')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá gốc')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Hãng')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Phần trăm giảm giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'San pham',
                'verbose_name_plural': 'San pham',
                'ordering': ['-created_at', '-is_featured'],
            },
        ),
    ]
