# Generated by Django 4.2.27 on 2026-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm'), ('amount', 'Số tiền cố định')], default='percent', max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá trị giảm')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn tối thiểu')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Giảm tối đa')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('usage_limit', models.IntegerField(default=100, verbose_name='Giới hạn sử dụng')),
                ('used_count', models.IntegerField(default=0, verbose_name='Đã sử dụng')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-end_date'],
            },
        ),
    ]
