# Generated by Django 4.2.27 on 2026-01-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Giảm giá (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_promotions', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Khuyến mãi đặc biệt',
                'verbose_name_plural': 'Khuyến mãi đặc biệt',
                'ordering': ['-created_at'],
            },
        ),
    ]
