# Generated by Django 4.2.27 on 2026-01-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_specialpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm nổi bật',
                'verbose_name_plural': 'Sản phẩm nổi bật',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
