# Generated by Django 4.2.27 on 2026-01-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_featuredproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
