# Generated by Django 4.2.27 on 2026-01-27 18:40

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_add_coupon_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Cập nhật cuối'),
            preserve_default=False,
        ),
    ]
