# Generated by Django 4.2.27 on 2026-01-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_add_coupon_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_open_box',
            field=models.BooleanField(default=False, verbose_name='Cho phép kiểm tra khi nhận hàng'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Tùy chọn màu sắc'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='Miễn phí vận chuyển'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Hết hàng'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy_30days',
            field=models.BooleanField(default=False, verbose_name='Chính sách đổi trả 30 ngày'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Thông số kỹ thuật'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Tùy chọn bộ nhớ'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Tùy chọn bảo hành'),
        ),
    ]
